import type { Event } from "@/lib/types"

// Simulated data fetching function
export async function fetchEvents(): Promise<Event[]> {
  // In a real app, this would be an API call
  // For now, we'll simulate a network delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return [
    {
      id: "1",
      title: "React Summit Brasil 2025",
      description:
        "O maior evento de React da América Latina, reunindo especialistas nacionais e internacionais para compartilhar conhecimento sobre React, React Native e todo o ecossistema.",
      date: new Date("2025-03-15T09:00:00"),
      location: "São Paulo, SP - Centro de Convenções",
      category: "Frontend",
      organizer: "TechConf Brasil",
      image: "/images/events/react-summit.jpg",
      capacity: 500,
      registeredAttendees: 478,
      isFeatured: true,
      tags: ["React", "JavaScript", "Frontend"],
    },
    {
      id: "2",
      title: "Python Conference 2025",
      description:
        "Três dias de palestras, tutoriais e networking com a comunidade Python do Brasil. Para iniciantes e especialistas.",
      date: new Date("2025-04-22T10:00:00"),
      location: "Rio de Janeiro, RJ - Hotel Windsor",
      category: "Backend",
      organizer: "Python Brasil",
      image: "/images/events/python-conf.jpg",
      capacity: 350,
      registeredAttendees: 187,
      isFeatured: false,
      tags: ["Python", "Data Science", "Backend"],
    },
    {
      id: "3",
      title: "DevOps Summit",
      description: "Aprenda as melhores práticas de DevOps, CI/CD, containers e muito mais com especialistas da área.",
      date: new Date("2025-02-12T08:30:00"),
      location: "Online",
      category: "DevOps",
      organizer: "Cloud Native Group",
      image: "/images/events/devops-summit.jpg",
      capacity: 1000,
      registeredAttendees: 456,
      isFeatured: true,
      tags: ["DevOps", "Kubernetes", "Docker", "CI/CD"],
    },
    {
      id: "4",
      title: "UX/UI Design Conference",
      description:
        "Evento focado em design de interfaces e experiência do usuário, com workshops práticos e palestras inspiradoras.",
      date: new Date("2025-05-05T09:00:00"),
      location: "Curitiba, PR - Expo Barigui",
      category: "Design",
      organizer: "Design Brasil",
      image: "/images/events/ux-conf.jpg",
      capacity: 250,
      registeredAttendees: 250,
      isFeatured: false,
      tags: ["UX", "UI", "Design"],
    },
    {
      id: "5",
      title: "AWS Community Day",
      description:
        "Um dia inteiro dedicado à AWS, com foco em serviços de nuvem, arquitetura serverless e boas práticas.",
      date: new Date("2025-02-28T10:00:00"),
      location: "Brasília, DF - Centro de Eventos",
      category: "Cloud",
      organizer: "AWS User Group",
      image: "/images/events/aws-day.jpg",
      capacity: 400,
      registeredAttendees: 210,
      isFeatured: false,
      tags: ["AWS", "Cloud", "Serverless"],
    },
    {
      id: "6",
      title: "Women in Tech Conference",
      description:
        "Conferência que celebra e incentiva a participação feminina na tecnologia, com palestras inspiradoras e networking.",
      date: new Date("2025-03-08T13:00:00"),
      location: "Recife, PE - Porto Digital",
      category: "Diversidade",
      organizer: "WomenTech Brasil",
      image: "/images/events/women-tech.jpg",
      capacity: 300,
      registeredAttendees: 285,
      isFeatured: true,
      tags: ["Diversidade", "Inclusão", "Carreira"],
    },
    {
      id: "7",
      title: "Mobile Dev Summit",
      description: "Evento dedicado ao desenvolvimento mobile, abordando iOS, Android, Flutter, React Native e mais.",
      date: new Date("2025-06-10T09:00:00"),
      location: "Belo Horizonte, MG - BH Plaza",
      category: "Mobile",
      organizer: "Mobile Devs Brasil",
      image: "/images/events/mobile-summit.jpg",
      capacity: 350,
      registeredAttendees: 124,
      isFeatured: false,
      tags: ["Mobile", "Android", "iOS", "Flutter"],
    },
    {
      id: "8",
      title: "Data Science Week",
      description: "Semana inteira dedicada à ciência de dados, inteligência artificial, machine learning e analytics.",
      date: new Date("2025-04-07T08:00:00"),
      location: "Florianópolis, SC - Tech Hub",
      category: "Data",
      organizer: "Data Science Academy",
      image: "/images/events/data-science.jpg",
      capacity: 450,
      registeredAttendees: 380,
      isFeatured: true,
      tags: ["Data Science", "AI", "Machine Learning"],
    },
    {
      id: "9",
      title: "Cybersecurity Conference",
      description:
        "Conferência sobre segurança da informação, com tópicos sobre privacidade, ethical hacking e defesa cibernética.",
      date: new Date("2025-05-20T10:00:00"),
      location: "Porto Alegre, RS - Centro de Convenções",
      category: "Segurança",
      organizer: "Secure Labs",
      image: "/images/events/cybersecurity.jpg",
      capacity: 300,
      registeredAttendees: 175,
      isFeatured: false,
      tags: ["Segurança", "Ethical Hacking", "Privacidade"],
    },
    {
      id: "10",
      title: "Hackathon de Inovação Social",
      description: "Hackathon focado no desenvolvimento de soluções tecnológicas para problemas sociais e ambientais.",
      date: new Date("2025-03-28T14:00:00"),
      location: "Salvador, BA - Parque Tecnológico",
      category: "Hackathon",
      organizer: "Social Tech Hub",
      image: "/images/events/hackathon.jpg",
      capacity: 150,
      registeredAttendees: 150,
      isFeatured: false,
      tags: ["Hackathon", "Impacto Social", "Inovação"],
    },
    {
      id: "11",
      title: "Blockchain & Web3 Summit",
      description: "Evento focado em blockchain, criptomoedas, NFTs e aplicações descentralizadas.",
      date: new Date("2025-07-15T09:00:00"),
      location: "São Paulo, SP - WTC",
      category: "Web3",
      organizer: "Blockchain Brasil",
      image: "/images/events/blockchain.jpg",
      capacity: 400,
      registeredAttendees: 187,
      isFeatured: true,
      tags: ["Blockchain", "Web3", "NFT", "DeFi"],
    },
    {
      id: "12",
      title: "Game Dev Experience",
      description: "Conferência para desenvolvedores de jogos, abordando design, programação, arte e monetização.",
      date: new Date("2025-08-05T10:00:00"),
      location: "Campinas, SP - Expo Dom Pedro",
      category: "Games",
      organizer: "Game Devs Brasil",
      image: "/images/events/gamedev.jpg",
      capacity: 250,
      registeredAttendees: 98,
      isFeatured: false,
      tags: ["Games", "Unity", "Unreal", "Game Design"],
    },
    {
      id: "13",
      title: "TechLeaders Summit",
      description:
        "Evento exclusivo para CTOs, gerentes de tecnologia e líderes técnicos discutirem tendências e desafios.",
      date: new Date("2025-04-18T08:30:00"),
      location: "Rio de Janeiro, RJ - Hotel Copacabana Palace",
      category: "Liderança",
      organizer: "Tech Leadership Network",
      image: "/images/events/techleaders.jpg",
      capacity: 200,
      registeredAttendees: 185,
      isFeatured: true,
      tags: ["Liderança", "Gestão", "Estratégia"],
    },
    {
      id: "14",
      title: "IoT & Smart Cities Forum",
      description:
        "Fórum sobre Internet das Coisas e aplicações para cidades inteligentes, com casos reais e discussões técnicas.",
      date: new Date("2025-06-25T09:00:00"),
      location: "Brasília, DF - Centro de Convenções Ulysses",
      category: "IoT",
      organizer: "Smart Brasil",
      image: "/images/events/iot-forum.jpg",
      capacity: 300,
      registeredAttendees: 145,
      isFeatured: false,
      tags: ["IoT", "Smart Cities", "Sensores", "Automação"],
    },
    {
      id: "15",
      title: "Agile Brazil Conference",
      description: "A maior conferência sobre métodos ágeis do Brasil, com foco em Scrum, Kanban, XP e cultura ágil.",
      date: new Date("2025-05-12T08:00:00"),
      location: "Fortaleza, CE - Centro de Eventos do Ceará",
      category: "Agilidade",
      organizer: "Agile Alliance Brasil",
      image: "/images/events/agile-conf.jpg",
      capacity: 450,
      registeredAttendees: 302,
      isFeatured: false,
      tags: ["Agile", "Scrum", "Kanban", "Liderança"],
    },
    {
      id: "16",
      title: "PHP Community Conference",
      description: "Conferência da comunidade PHP brasileira, com palestras sobre Laravel, Symfony, WordPress e mais.",
      date: new Date("2025-04-30T09:30:00"),
      location: "Curitiba, PR - Positivo Campus",
      category: "Backend",
      organizer: "PHP Brasil",
      image: "/images/events/php-conf.jpg",
      capacity: 250,
      registeredAttendees: 98,
      isFeatured: false,
      tags: ["PHP", "Laravel", "Symfony", "Backend"],
    },
    {
      id: "17",
      title: "AI in Healthcare Symposium",
      description:
        "Simpósio sobre aplicações de inteligência artificial na saúde, reunindo profissionais de tecnologia e medicina.",
      date: new Date("2025-07-08T10:00:00"),
      location: "São Paulo, SP - Hospital Sírio-Libanês",
      category: "HealthTech",
      organizer: "Health Innovation Hub",
      image: "/images/events/ai-health.jpg",
      capacity: 200,
      registeredAttendees: 200,
      isFeatured: true,
      tags: ["IA", "Saúde", "HealthTech", "Inovação"],
    },
    {
      id: "18",
      title: "E-commerce & Digital Marketing Summit",
      description: "Evento focado em tecnologias e estratégias para e-commerce e marketing digital.",
      date: new Date("2025-03-25T09:00:00"),
      location: "Online",
      category: "E-commerce",
      organizer: "Digital Business Association",
      image: "/images/events/ecommerce.jpg",
      capacity: 800,
      registeredAttendees: 456,
      isFeatured: false,
      tags: ["E-commerce", "Marketing Digital", "SEO", "Analytics"],
    },
    {
      id: "19",
      title: "Open Source Community Day",
      description: "Evento dedicado a projetos e comunidades open source, com contribuições ao vivo e workshops.",
      date: new Date("2025-06-18T13:00:00"),
      location: "Porto Alegre, RS - UFRGS Campus Central",
      category: "Open Source",
      organizer: "Open Source Initiative Brasil",
      image: "/images/events/opensource.jpg",
      capacity: 300,
      registeredAttendees: 123,
      isFeatured: false,
      tags: ["Open Source", "Comunidade", "Software Livre"],
    },
    {
      id: "20",
      title: "Startup Summit Brasil",
      description: "O maior evento para startups do Brasil, com pitches, mentorias, investidores e networking.",
      date: new Date("2025-05-28T08:00:00"),
      location: "Belo Horizonte, MG - BH Station",
      category: "Startups",
      organizer: "Startup Brasil",
      image: "/images/events/startup-summit.jpg",
      capacity: 500,
      registeredAttendees: 487,
      isFeatured: true,
      tags: ["Startups", "Empreendedorismo", "Inovação", "Investimentos"],
    },
    {
      id: "21",
      title: "Java Developer Conference",
      description:
        "Conferência dedicada ao ecossistema Java, com foco em Spring, Micronaut, Quarkus e tendências futuras.",
      date: new Date("2025-09-10T09:00:00"),
      location: "Recife, PE - CESAR",
      category: "Backend",
      organizer: "Java User Group Brasil",
      image: "/images/events/java-conf.jpg",
      capacity: 350,
      registeredAttendees: 245,
      isFeatured: false,
      tags: ["Java", "Spring", "JVM", "Backend"],
    },
    {
      id: "22",
      title: "Low-Code No-Code Conference",
      description: "Evento sobre plataformas e ferramentas low-code e no-code para desenvolvimento ágil de aplicações.",
      date: new Date("2025-06-05T10:00:00"),
      location: "São Paulo, SP - Expo Center Norte",
      category: "Low-Code",
      organizer: "Code Revolution",
      image: "/images/events/lowcode.jpg",
      capacity: 250,
      registeredAttendees: 137,
      isFeatured: false,
      tags: ["Low-Code", "No-Code", "Produtividade", "Desenvolvimento Rápido"],
    },
    {
      id: "23",
      title: "Robótica & IA Expo",
      description:
        "Exposição de robótica, inteligência artificial e automação, com demonstrações ao vivo e competições.",
      date: new Date("2025-08-22T09:00:00"),
      location: "Campinas, SP - Unicamp",
      category: "Robótica",
      organizer: "Brazilian Robotics Association",
      image: "/images/events/robotics.jpg",
      capacity: 400,
      registeredAttendees: 267,
      isFeatured: true,
      tags: ["Robótica", "IA", "Automação", "Hardware"],
    },
    {
      id: "24",
      title: "Acessibilidade na Web Meetup",
      description:
        "Encontro sobre práticas de acessibilidade digital, WCAG, design inclusivo e tecnologias assistivas.",
      date: new Date("2025-04-15T18:30:00"),
      location: "Online",
      category: "Acessibilidade",
      organizer: "Web para Todos",
      image: "/images/events/accessibility.jpg",
      capacity: 200,
      registeredAttendees: 86,
      isFeatured: false,
      tags: ["Acessibilidade", "Inclusão", "Design", "Web"],
    },
    {
      id: "25",
      title: "NextJS & React Framework Day",
      description: "Evento dedicado ao NextJS e outros frameworks React, com palestras e casos de uso reais.",
      date: new Date("2025-07-25T09:00:00"),
      location: "Florianópolis, SC - Link Coworking",
      category: "Frontend",
      organizer: "Frontend Masters Brasil",
      image: "/images/events/nextjs-day.jpg",
      capacity: 150,
      registeredAttendees: 150,
      isFeatured: false,
      tags: ["NextJS", "React", "Frontend", "JavaScript"],
    },
  ]
}

export async function fetchEventById(id: string): Promise<Event | null> {
  const events = await fetchEvents()
  return events.find((event) => event.id === id) || null
}
